version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/otpdb
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    depends_on:
      - mongo
      - mailhog

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # web UI at http://localhost:8025

volumes:
  mongo_data:
    driver: local 

    